### ISSUE TITLE
Wrong shortcut in Chapter 2_2

### ISSUE THREAD

**Issue by phr34ck** [jaipandya/SublimeTutor#1]
Exercise 2 should be `Option + Delete` and not `Cmd + Delete`. `Cmd + Delete` deletes from the cursor to the beginning of the line.

**Comment by jaipandya** [comment]
Hi @phr34ck

Thanks for filing an issue. Given that you are one of the early users of SublimeTutor, would love to get some more feedback. How was your experience going through the chapters, how long did it take you to complete the exercises etc. My email ID is hello [at] jai [dot] im

**Comment by sudarsangp** [comment]
There are similar errors in chapter 2_3, 2_4 and 2_5. Created a [PR](https://github.com/jaipandya/SublimeTutor/pull/5)
