### ISSUE TITLE
typo in tuturial 

### ISSUE THREAD

**Issue by kivS** [jaipandya/SublimeTutor#20]
Hi there,

**Branch:** win/linux
**File:** chapter_5_1.md

> 4.Cycle in the opposite order using **`Alt + F3`**, press this multiple times
>    until you get comfortable with this command.

Should be:  **Shift + F3**

**Comment by jaipandya** [comment]
Thanks for your input @kivS. Commit https://github.com/jaipandya/SublimeTutor/commit/642e677d65972cbb7266b4cc76cbcbcd1862b180 fixes this.
