### ISSUE TITLE
Installed, but won't launch

### ISSUE THREAD

**Issue by mikechia** [jaipandya/SublimeTutor#21]
I went through the steps to install SublimeTutor but when I attempt to launch it I see:

```
Traceback (most recent call last):
  File "./sublime_plugin.py", line 339, in run_
  File "./sublime_tutor.py", line 19, in run
AttributeError: 'module' object has no attribute 'executable_path'
```

**Comment by jaipandya** [comment]
Hi @mikechia, could you list your OS and Sublime Text version here. I can't reproduce it on Mac.

**Comment by jaipandya** [comment]
Closing the bug due to inactivity.
