### ISSUE TITLE
Something is wrong in chapter 5.3

### ISSUE THREAD

**Issue by Climber24** [jaipandya/SublimeTutor#25]
In the second exercise there is "4. Now press `Ctrl + Shift + E` three times, this should replace all three
   strings with an empty one." item. It seems that there is something wrong here because Ctrl + Shift + E shortcut does not replace anything.

**Comment by lovubuntu** [comment]
It should actually be tilde (~) instead of underscores (_) that we are trying to replace. Maybe a typo I guess.

**Comment by jaipandya** [comment]
The latest update that's going to be pushed soon, should fix it.

**Comment by jaipandya** [comment]
This issue was fixed in https://github.com/jaipandya/SublimeTutor/commit/10dd83e8d01340972b9e5869da340184011a8aa5
