### ISSUE TITLE
Not found in Package Control

### ISSUE THREAD

**Issue by ghost** [jaipandya/SublimeTutor#33]
As written in the title above, I can't find Sublime tutor via Package Control.
Is there a problem or is it only me?

<img width="464" alt="screen shot 2017-04-14 at 14 39 35" src="https://cloud.githubusercontent.com/assets/26062128/25043462/83f66460-2120-11e7-8f8c-e8083cc11386.png">

**Comment by jaipandya** [comment]
Works fine for me. What is the version of your Sublime Text and platform?

**Comment by ghost** [comment]
Solved! I had it already installed 😮
