### ISSUE TITLE
Uncommenting not working in Chapter 2.12

### ISSUE THREAD

**Issue by Kreeblah** [jaipandya/SublimeTutor#34]
Maybe I'm doing something wrong here, but uncommenting with Cmd+/ doesn't seem to be working in chapter 2.12.  All I'm getting is successive layers of HTML-styled comments.

For example, I go from:

```  <!-- <li>first list item</li> -->```

to:

```  <!-- <!-- <li>first list item</li> --> -->```

And I keep adding further layers of comment tags from there.  Should I be doing something else here?  I'm running Sublime Text build 3142 on macOS 10.12.6, if it matters.

**Comment by assarbad** [comment]
The same happens on Windows with `Ctrl + /`, so I guess something has changed in the program or the tutorial is wrong about the shortcut.

An alternative explanation could be some plugins we use, which break the default behavior of ST3.

**Comment by jaipandya** [comment]
Seems like HTML text wrapped in a code block (```) behaves in a different way. If you remove the backticks from above and below the code segment, it works as expected. Once fixed, markdown will try to render it as valid HTML, so elsewhere it would create a problem. But I guess, that should be okay.

I've decided to change the HTML syntax to JavaScript. That solves this issue. Look for an update soon.

**Comment by jaipandya** [comment]
This issue was fixed in https://github.com/jaipandya/SublimeTutor/commit/8b9a8b5fe772d389552513e46ddb6932efb6610b
